forge "http://forge.puppetlabs.com"

mod "puppetlabs/apache"
mod "puppetlabs/firewall"
mod "example42/mysql"
mod "thias/php"
mod "example42/yum"
mod "example42/puppi"

mod "puppetlabs/stdlib"
mod "puppetlabs/concat"

#mod "stdlib",
#  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
